name: cmv-pipeline
channels:
  - bioconda
  - conda-forge
  - defaults

dependencies:
  # ---- Python runtime ----
  - python=3.11
  - pip
  - pandas>=2.2,<3
  - numpy>=1.26
  - matplotlib>=3.8
  - seaborn>=0.13
  - pysam>=0.22
  - tk                    # tkinter for the GUI

  # ---- CLI tools used in your bash scripts ----
  - blast>=2.13           # provides blastn
  - seqtk>=1.3
  - bwa>=0.7.17
  - samtools>=1.18
  - picard>=3.0
  - fastqc>=0.12
  - trim-galore>=0.6
  - cutadapt>=4.0
  - parallel
  - pigz
  - pbzip2
  - gzip
  - coreutils             # provides stdbuf

  - openjdk>=17           # for Picard

  # ---- Optional (for GUI IGV launch) ----
  # - igv
