name: CMV_Project
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - bash=5.0.018
  - curl=8.1.2
  - wget=1.21.4
  - git=2.42.0
  - parallel=20250422
  - trim-galore=0.6.10
  - fastuniq=1.1
  - fastqc=0.12.1
  - samtools=1.6
  - bowtie2=2.5.4
  - trimmomatic=0.39
  - picard=3.4.0
  - bedtools=2.31.1
  - htslib=1.3.1
  - blast=2.12.0
  - seqtk=1.4
  - python=3.11.11
  - pip=25.0
  - xopen=2.0.2
  - r-base=4.2.3
