#!/usr/bin/env python3
"""
sample_validation_design_graphs.py

Purpose
-------
Create validation outputs that show, in graph form, what the ART Illumina
simulation was designed to create and what the downstream CMV pipeline
actually observed.

This is designed for sample sets generated by b_generate_roc_sampleset.py,
where the truth metadata already stores the simulated composition of each
sample (CMV pairs, other-virus pairs, human pairs, total pairs, target CMV
fraction, mutation spike metadata). The script then compares that intended
design with observed pipeline outputs from three separate result directories.

Key idea
--------
"Expected" in this script means the simulated composition written to
truth/metadata.tsv by the ART Illumina generation script.

"Observed" means what the CMV pipeline measured for the same sample:
- high-quality CMV mapped read count / RPM
- CMV breadth
- CMV BLAST identity

Outputs
-------
Tables
- simulation_design_table.tsv
- sample_expected_vs_observed.tsv
- group_expected_vs_observed_summary.tsv

Figures
- figures/group_expected_vs_observed_overview.png
- figures/sample_expected_vs_observed_proxy_fraction.png
- figures/roc_ladder_expected_vs_observed.png
- figures/sample_composition_expected.png

Notes
-----
Observed CMV fraction is estimated as a proxy:
    observed_cmv_pair_fraction_proxy = (cmv_mapped_reads_mapq / 2) / total_pairs

This is not a true reconstruction of the original ART composition because
pipeline filtering and mapping reduce the read count, but it is a simple and
interpretable way to compare intended CMV content with what was recovered.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path
from typing import Iterable, List

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


_SUFFIX_PATTERNS = [
    r"(?:_R?[12](?:_00[1-9])?)$",
    r"(?:_[12])$",
    r"(?:_sorted(?:_sorted)*)$",
    r"(?:_sort(?:ed)?)$",
    r"(?:_dedup(?:ed)?)$",
    r"(?:_mark(?:ed)?dups?)$",
    r"(?:_rmdup[s]?)$",
    r"(?:_trim(?:med)?(?:_paired)?)$",
    r"(?:_filtered)$",
    r"(?:_indelqual)$",
    r"(?:_realigned)$",
    r"(?:\.bam)$",
]

GROUP_ORDER = [
    "NEG_HUMAN_ONLY",
    "NEG_OTHER_VIRUS",
    "NEG_CONTAM",
    "POS_ROC_LADDER",
    "POS_CMV_PLUS_OTHER",
    "POS_MIXED_STRAINS",
    "POS_MUT_SPIKE",
]


def canonical_sample(name: str) -> str:
    s = str(name)
    changed = True
    while changed:
        changed = False
        for pat in _SUFFIX_PATTERNS:
            new = re.sub(pat, "", s, flags=re.IGNORECASE)
            if new != s:
                s = new
                changed = True
    return s.rstrip("_-")


def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def read_table(path: Path) -> pd.DataFrame:
    if not path.exists() or path.stat().st_size == 0:
        return pd.DataFrame()
    for sep in ["\t", ","]:
        try:
            df = pd.read_csv(path, sep=sep, low_memory=False)
            if df.shape[1] >= 2:
                return df
        except Exception:
            pass
    try:
        return pd.read_csv(path, sep=None, engine="python", low_memory=False)
    except Exception:
        return pd.DataFrame()


def read_glob(files: Iterable[Path]) -> pd.DataFrame:
    dfs: List[pd.DataFrame] = []
    for p in files:
        df = read_table(p)
        if not df.empty:
            dfs.append(df)
    return pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame()


def coerce_numeric(df: pd.DataFrame, cols: Iterable[str]) -> pd.DataFrame:
    out = df.copy()
    for c in cols:
        if c in out.columns:
            out[c] = pd.to_numeric(out[c], errors="coerce")
    return out


def sum_maybe_comma_numbers(val) -> float:
    if pd.isna(val):
        return np.nan
    s = str(val).strip()
    if not s or s.lower() == "nan":
        return np.nan
    total = 0.0
    found = False
    for part in s.split(","):
        part = part.strip()
        if not part:
            continue
        try:
            total += float(part)
            found = True
        except Exception:
            continue
    return total if found else np.nan


def collect_csv_dirs(args: argparse.Namespace) -> List[Path]:
    return [Path(args.csv_dir_1), Path(args.csv_dir_2), Path(args.csv_dir_3)]


def load_truth(metadata_tsv: Path) -> pd.DataFrame:
    df = read_table(metadata_tsv)
    if df.empty:
        raise SystemExit(f"Could not read truth metadata: {metadata_tsv}")

    required = ["sample", "group", "truth_cmv_present", "total_pairs"]
    missing = [c for c in required if c not in df.columns]
    if missing:
        raise SystemExit(f"Truth metadata missing columns: {', '.join(missing)}")

    df["base"] = df["sample"].astype(str).apply(canonical_sample)

    numeric_cols = [
        "truth_cmv_present", "cmv_fraction_target", "total_pairs",
        "human_pairs", "read_len", "mean_frag", "sd_frag",
        "snv_rate", "random_snv_count", "mutation_af_target"
    ]
    df = coerce_numeric(df, numeric_cols)

    if "cmv_pairs" in df.columns:
        df["cmv_pairs_total_expected"] = df["cmv_pairs"].apply(sum_maybe_comma_numbers)
    else:
        df["cmv_pairs_total_expected"] = np.nan

    if "other_pairs" in df.columns:
        df["other_pairs_total_expected"] = df["other_pairs"].apply(sum_maybe_comma_numbers)
    else:
        df["other_pairs_total_expected"] = np.nan

    if "human_pairs" not in df.columns:
        df["human_pairs"] = np.nan

    df["human_pairs_total_expected"] = pd.to_numeric(df["human_pairs"], errors="coerce")

    if "cmv_fraction_target" not in df.columns or df["cmv_fraction_target"].isna().all():
        df["cmv_fraction_target"] = (
            df["cmv_pairs_total_expected"] / df["total_pairs"].replace({0: np.nan})
        )

    df["expected_cmv_fraction"] = df["cmv_pairs_total_expected"] / df["total_pairs"].replace({0: np.nan})
    df["expected_other_fraction"] = df["other_pairs_total_expected"] / df["total_pairs"].replace({0: np.nan})
    df["expected_human_fraction"] = df["human_pairs_total_expected"] / df["total_pairs"].replace({0: np.nan})

    keep = [
        "sample", "base", "group", "truth_cmv_present",
        "cmv_fraction_target", "expected_cmv_fraction", "expected_other_fraction",
        "expected_human_fraction", "total_pairs", "cmv_refs", "cmv_pairs",
        "cmv_pairs_total_expected", "other_refs", "other_pairs", "other_pairs_total_expected",
        "human_ref", "human_pairs_total_expected", "read_len", "seq_sys",
        "mean_frag", "sd_frag", "snv_rate", "random_snv_count",
        "mutation_spiked", "mutation_af_target", "mutations_applied",
    ]
    keep = [c for c in keep if c in df.columns]
    out = df[keep].drop_duplicates("base").copy()
    return out


def load_alignment_summaries(csv_dirs: List[Path]) -> pd.DataFrame:
    files: List[Path] = []
    for d in csv_dirs:
        if not d.exists():
            print(f"Warning: alignment directory not found: {d}")
            continue
        preferred = d / "cmv_alignment_summary.csv"
        if preferred.exists():
            files.append(preferred)
        else:
            files.extend(sorted(d.glob("*_summary.csv")))
            files.extend(sorted(d.glob("summary.csv")))

    df = read_glob(files)
    if df.empty:
        return df

    if "base" not in df.columns:
        if "sample" in df.columns:
            df["base"] = df["sample"].astype(str).apply(canonical_sample)
        else:
            df["base"] = df.iloc[:, 0].astype(str).apply(canonical_sample)

    df["base"] = df["base"].astype(str).apply(canonical_sample)
    df = coerce_numeric(df, [
        "cmv_mapped_reads_mapq", "cmv_rpm_mapq", "cmv_breadth_mapq",
        "cmv_cov_bases_mapq", "cmv_ref_bases", "total_reads_in_cmv_bam"
    ])

    agg = {}
    for col in ["cmv_mapped_reads_mapq", "cmv_cov_bases_mapq", "total_reads_in_cmv_bam"]:
        if col in df.columns:
            agg[col] = "sum"
    for col in ["cmv_rpm_mapq", "cmv_breadth_mapq", "cmv_ref_bases"]:
        if col in df.columns:
            agg[col] = "max"

    out = df.groupby("base", as_index=False).agg(agg) if agg else df[["base"]].drop_duplicates()
    if "cmv_mapped_reads_mapq" in out.columns:
        out["log10_mapped_hq"] = np.log10(out["cmv_mapped_reads_mapq"].replace({0: np.nan}))
    if "cmv_rpm_mapq" in out.columns:
        out["log10_rpm_hq"] = np.log10(out["cmv_rpm_mapq"].replace({0: np.nan}))
    if {"cmv_cov_bases_mapq", "cmv_ref_bases"}.issubset(out.columns):
        out["cmv_breadth_from_cov"] = out["cmv_cov_bases_mapq"] / out["cmv_ref_bases"].replace({0: np.nan})
    return out


def load_blast_top5(csv_dirs: List[Path]) -> pd.DataFrame:
    files: List[Path] = []
    for d in csv_dirs:
        if d.exists():
            files.extend(sorted(d.glob("*_blast_top5.csv")))
    df = read_glob(files)
    if df.empty:
        return df

    if "base" not in df.columns:
        if "sample" in df.columns:
            df["base"] = df["sample"].astype(str).apply(canonical_sample)
        else:
            raise SystemExit("BLAST top5 table missing 'base' or 'sample' column.")

    df["base"] = df["base"].astype(str).apply(canonical_sample)
    df = coerce_numeric(df, ["total_hits", "avg_identity"])

    species = df["species"].astype(str) if "species" in df.columns else pd.Series("", index=df.index)
    is_cmv = species.str.contains("herpesvirus 5|cytomegalovirus|merlin|hcmv", case=False, na=False)

    rows = []
    for base, sub in df.groupby("base"):
        cmv_sub = sub[is_cmv.loc[sub.index]]
        if cmv_sub.empty:
            rows.append({
                "base": base,
                "blast_cmv_hits_top5": 0,
                "blast_cmv_mean_identity_top5": np.nan,
            })
        else:
            if "total_hits" in cmv_sub.columns and float(cmv_sub["total_hits"].sum()) > 0:
                weights = cmv_sub["total_hits"].to_numpy(dtype=float)
                mean_identity = float(np.average(cmv_sub["avg_identity"].to_numpy(dtype=float), weights=weights))
                hit_count = int(cmv_sub["total_hits"].sum())
            else:
                mean_identity = float(cmv_sub["avg_identity"].mean())
                hit_count = int(len(cmv_sub))
            rows.append({
                "base": base,
                "blast_cmv_hits_top5": hit_count,
                "blast_cmv_mean_identity_top5": mean_identity,
            })
    return pd.DataFrame(rows)


def build_expected_vs_observed_table(truth: pd.DataFrame, bam: pd.DataFrame, blast: pd.DataFrame) -> pd.DataFrame:
    df = truth.copy()
    if bam is not None and not bam.empty:
        df = df.merge(bam, on="base", how="left")
    if blast is not None and not blast.empty:
        df = df.merge(blast, on="base", how="left")

    df["observed_cmv_pair_fraction_proxy"] = (
        pd.to_numeric(df.get("cmv_mapped_reads_mapq"), errors="coerce") / 2.0
    ) / pd.to_numeric(df.get("total_pairs"), errors="coerce").replace({0: np.nan})

    df["observed_minus_expected_fraction_proxy"] = (
        df["observed_cmv_pair_fraction_proxy"] - df["expected_cmv_fraction"]
    )

    def design_text(row: pd.Series) -> str:
        g = str(row.get("group", ""))
        ec = row.get("expected_cmv_fraction", np.nan)
        eo = row.get("expected_other_fraction", np.nan)
        eh = row.get("expected_human_fraction", np.nan)
        mut = row.get("mutation_af_target", np.nan)

        bits = []
        if pd.notna(ec):
            bits.append(f"CMV {ec:.3g}")
        if pd.notna(eo):
            bits.append(f"other {eo:.3g}")
        if pd.notna(eh):
            bits.append(f"human {eh:.3g}")
        if g == "POS_MUT_SPIKE" and pd.notna(mut):
            bits.append(f"mut AF {mut:.2f}")
        return ", ".join(bits)

    def observed_text(row: pd.Series) -> str:
        bits = []
        f = row.get("observed_cmv_pair_fraction_proxy", np.nan)
        r = row.get("log10_rpm_hq", np.nan)
        b = row.get("cmv_breadth_mapq", np.nan)
        i = row.get("blast_cmv_mean_identity_top5", np.nan)
        if pd.notna(f):
            bits.append(f"CMV proxy {f:.3g}")
        if pd.notna(r):
            bits.append(f"log10 RPM {r:.2f}")
        if pd.notna(b):
            bits.append(f"breadth {b:.4f}")
        if pd.notna(i):
            bits.append(f"id {i:.1f}%")
        return ", ".join(bits)

    df["expected_design_summary"] = df.apply(design_text, axis=1)
    df["observed_summary"] = df.apply(observed_text, axis=1)

    cols = [
        "sample", "group", "truth_cmv_present",
        "expected_design_summary", "observed_summary",
        "total_pairs",
        "cmv_fraction_target", "expected_cmv_fraction",
        "expected_other_fraction", "expected_human_fraction",
        "cmv_pairs_total_expected", "other_pairs_total_expected", "human_pairs_total_expected",
        "observed_cmv_pair_fraction_proxy", "observed_minus_expected_fraction_proxy",
        "cmv_mapped_reads_mapq", "log10_rpm_hq", "cmv_breadth_mapq",
        "blast_cmv_hits_top5", "blast_cmv_mean_identity_top5",
        "mutation_spiked", "mutation_af_target", "mutations_applied",
    ]
    cols = [c for c in cols if c in df.columns]
    out = df[cols].copy()

    out["group"] = pd.Categorical(out["group"], categories=GROUP_ORDER, ordered=True)
    out = out.sort_values(["group", "sample"]).reset_index(drop=True)
    return out


def build_group_summary(df: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for group, sub in df.groupby("group", dropna=False):
        row = {
            "group": group,
            "n_samples": len(sub),
            "median_expected_cmv_fraction": pd.to_numeric(sub["expected_cmv_fraction"], errors="coerce").median() if "expected_cmv_fraction" in sub else np.nan,
            "median_expected_other_fraction": pd.to_numeric(sub["expected_other_fraction"], errors="coerce").median() if "expected_other_fraction" in sub else np.nan,
            "median_expected_human_fraction": pd.to_numeric(sub["expected_human_fraction"], errors="coerce").median() if "expected_human_fraction" in sub else np.nan,
            "median_observed_cmv_pair_fraction_proxy": pd.to_numeric(sub["observed_cmv_pair_fraction_proxy"], errors="coerce").median() if "observed_cmv_pair_fraction_proxy" in sub else np.nan,
            "median_log10_rpm_hq": pd.to_numeric(sub["log10_rpm_hq"], errors="coerce").median() if "log10_rpm_hq" in sub else np.nan,
            "median_cmv_breadth_mapq": pd.to_numeric(sub["cmv_breadth_mapq"], errors="coerce").median() if "cmv_breadth_mapq" in sub else np.nan,
            "median_blast_identity": pd.to_numeric(sub["blast_cmv_mean_identity_top5"], errors="coerce").median() if "blast_cmv_mean_identity_top5" in sub else np.nan,
        }
        rows.append(row)
    out = pd.DataFrame(rows)
    out["group"] = pd.Categorical(out["group"], categories=GROUP_ORDER, ordered=True)
    out = out.sort_values("group").reset_index(drop=True)
    return out


def plot_group_expected_vs_observed_overview(group_df: pd.DataFrame, outpath: Path) -> None:
    if group_df.empty:
        return

    groups = group_df["group"].astype(str).tolist()
    y = np.arange(len(groups))

    fig, axes = plt.subplots(
        nrows=1, ncols=4, figsize=(18, max(5, 0.65 * len(groups) + 2)),
        gridspec_kw={"width_ratios": [2.3, 1.4, 1.2, 1.2]}
    )

    # Panel 1: expected composition stacked bars
    ax = axes[0]
    human = pd.to_numeric(group_df["median_expected_human_fraction"], errors="coerce").fillna(0)
    other = pd.to_numeric(group_df["median_expected_other_fraction"], errors="coerce").fillna(0)
    cmv = pd.to_numeric(group_df["median_expected_cmv_fraction"], errors="coerce").fillna(0)
    ax.barh(y, human, label="Expected human")
    ax.barh(y, other, left=human, label="Expected other virus")
    ax.barh(y, cmv, left=human + other, label="Expected CMV")
    ax.set_xlim(0, 1)
    ax.set_yticks(y)
    ax.set_yticklabels(groups)
    ax.invert_yaxis()
    ax.set_xlabel("Expected fraction of sample")
    ax.set_title("What the ART script was told to create")
    ax.legend(frameon=False, fontsize=8, loc="lower right")

    # Panel 2: observed CMV recovery proxy
    ax = axes[1]
    obs = pd.to_numeric(group_df["median_observed_cmv_pair_fraction_proxy"], errors="coerce")
    obs = obs.replace({0: np.nan})
    ax.barh(y, obs)
    ax.set_xscale("log")
    ax.set_yticks(y)
    ax.set_yticklabels([])
    ax.invert_yaxis()
    ax.set_xlabel("Observed CMV pair fraction proxy")
    ax.set_title("What the pipeline recovered")

    # Panel 3: observed breadth
    ax = axes[2]
    breadth = pd.to_numeric(group_df["median_cmv_breadth_mapq"], errors="coerce")
    ax.barh(y, breadth)
    ax.set_yticks(y)
    ax.set_yticklabels([])
    ax.invert_yaxis()
    ax.set_xlabel("Observed CMV breadth")
    ax.set_title("Observed breadth")

    # Panel 4: observed BLAST identity
    ax = axes[3]
    ident = pd.to_numeric(group_df["median_blast_identity"], errors="coerce")
    ax.barh(y, ident)
    ax.set_yticks(y)
    ax.set_yticklabels([])
    ax.invert_yaxis()
    ax.set_xlabel("Observed BLAST identity (%)")
    ax.set_title("Observed identity")

    fig.suptitle("Expected simulation design versus observed CMV evidence by group", y=1.02)
    fig.tight_layout()
    fig.savefig(outpath, dpi=300, bbox_inches="tight")
    plt.close(fig)


def plot_sample_expected_vs_observed_proxy_fraction(df: pd.DataFrame, outpath: Path) -> None:
    need = {"expected_cmv_fraction", "observed_cmv_pair_fraction_proxy", "group"}
    if not need.issubset(df.columns):
        return

    sub = df.copy()
    sub["expected_cmv_fraction"] = pd.to_numeric(sub["expected_cmv_fraction"], errors="coerce")
    sub["observed_cmv_pair_fraction_proxy"] = pd.to_numeric(sub["observed_cmv_pair_fraction_proxy"], errors="coerce")
    sub = sub.dropna(subset=["expected_cmv_fraction", "observed_cmv_pair_fraction_proxy"])
    sub = sub[(sub["expected_cmv_fraction"] > 0) & (sub["observed_cmv_pair_fraction_proxy"] > 0)]
    if sub.empty:
        return

    fig, ax = plt.subplots(figsize=(8, 6))
    for group in GROUP_ORDER:
        gsub = sub[sub["group"].astype(str) == group]
        if gsub.empty:
            continue
        ax.scatter(
            gsub["expected_cmv_fraction"],
            gsub["observed_cmv_pair_fraction_proxy"],
            label=group,
            alpha=0.9,
        )

    # reference line
    lo = min(sub["expected_cmv_fraction"].min(), sub["observed_cmv_pair_fraction_proxy"].min())
    hi = max(sub["expected_cmv_fraction"].max(), sub["observed_cmv_pair_fraction_proxy"].max())
    ax.plot([lo, hi], [lo, hi], linestyle="--", linewidth=1)

    ax.set_xscale("log")
    ax.set_yscale("log")
    ax.set_xlabel("Expected CMV fraction from simulation metadata")
    ax.set_ylabel("Observed CMV pair fraction proxy")
    ax.set_title("Per-sample expected versus observed CMV content")
    ax.legend(frameon=False, fontsize=8)
    fig.tight_layout()
    fig.savefig(outpath, dpi=300, bbox_inches="tight")
    plt.close(fig)


def plot_roc_ladder_expected_vs_observed(df: pd.DataFrame, outpath: Path) -> None:
    need = {"group", "expected_cmv_fraction", "observed_cmv_pair_fraction_proxy", "cmv_breadth_mapq"}
    if not need.issubset(df.columns):
        return

    sub = df[df["group"].astype(str) == "POS_ROC_LADDER"].copy()
    sub["expected_cmv_fraction"] = pd.to_numeric(sub["expected_cmv_fraction"], errors="coerce")
    sub["observed_cmv_pair_fraction_proxy"] = pd.to_numeric(sub["observed_cmv_pair_fraction_proxy"], errors="coerce")
    sub["cmv_breadth_mapq"] = pd.to_numeric(sub["cmv_breadth_mapq"], errors="coerce")
    sub = sub.dropna(subset=["expected_cmv_fraction"])
    if sub.empty:
        return

    fig, axes = plt.subplots(nrows=1, ncols=2, figsize=(12, 5))

    ax = axes[0]
    scat = sub.dropna(subset=["observed_cmv_pair_fraction_proxy"])
    if not scat.empty:
        ax.scatter(scat["expected_cmv_fraction"], scat["observed_cmv_pair_fraction_proxy"])
        ax.set_yscale("log")
    ax.set_xscale("log")
    ax.set_xlabel("Expected CMV fraction")
    ax.set_ylabel("Observed CMV pair fraction proxy")
    ax.set_title("ROC ladder: expected vs observed CMV fraction")

    ax = axes[1]
    scat = sub.dropna(subset=["cmv_breadth_mapq"])
    if not scat.empty:
        ax.scatter(scat["expected_cmv_fraction"], scat["cmv_breadth_mapq"])
    ax.set_xscale("log")
    ax.set_xlabel("Expected CMV fraction")
    ax.set_ylabel("Observed CMV breadth")
    ax.set_title("ROC ladder: expected fraction vs observed breadth")

    fig.tight_layout()
    fig.savefig(outpath, dpi=300, bbox_inches="tight")
    plt.close(fig)


def plot_sample_composition_expected(df: pd.DataFrame, outpath: Path, max_samples: int = 80) -> None:
    need = {"sample", "group", "expected_cmv_fraction", "expected_other_fraction", "expected_human_fraction"}
    if not need.issubset(df.columns):
        return

    plot_df = df.copy()
    plot_df["group"] = pd.Categorical(plot_df["group"], categories=GROUP_ORDER, ordered=True)
    plot_df = plot_df.sort_values(["group", "sample"]).reset_index(drop=True)
    if len(plot_df) > max_samples:
        plot_df = plot_df.iloc[:max_samples].copy()

    y = np.arange(len(plot_df))
    human = pd.to_numeric(plot_df["expected_human_fraction"], errors="coerce").fillna(0)
    other = pd.to_numeric(plot_df["expected_other_fraction"], errors="coerce").fillna(0)
    cmv = pd.to_numeric(plot_df["expected_cmv_fraction"], errors="coerce").fillna(0)

    fig_h = max(8, 0.22 * len(plot_df) + 2)
    fig, ax = plt.subplots(figsize=(11, fig_h))
    ax.barh(y, human, label="Expected human")
    ax.barh(y, other, left=human, label="Expected other virus")
    ax.barh(y, cmv, left=human + other, label="Expected CMV")
    ax.set_xlim(0, 1)
    ax.set_yticks(y)
    ax.set_yticklabels(plot_df["sample"].astype(str))
    ax.invert_yaxis()
    ax.set_xlabel("Expected fraction of sample")
    ax.set_title("Expected simulated composition per sample")

    prev = None
    for i, g in enumerate(plot_df["group"].astype(str)):
        if prev is not None and g != prev:
            ax.axhline(i - 0.5, linewidth=1)
        prev = g

    ax.legend(frameon=False, loc="lower right")
    fig.tight_layout()
    fig.savefig(outpath, dpi=300, bbox_inches="tight")
    plt.close(fig)


def write_readme(outdir: Path) -> None:
    text = """
How to interpret these outputs
==============================

simulation_design_table.tsv
- The intended simulated composition written by the ART Illumina generation script.

sample_expected_vs_observed.tsv
- Per-sample comparison between expected composition and observed CMV evidence.

group_expected_vs_observed_summary.tsv
- Group-level medians used for the overview figure.

Important point
---------------
The expected side comes directly from the simulation metadata.
The observed side comes from the downstream CMV pipeline.

Observed CMV fraction is shown as a proxy:
    (high-quality CMV mapped reads / 2) / total simulated pairs

This makes the comparison easier to understand, but it is not a perfect
reconstruction of the original ART output because alignment and filtering
change the recovered read count.
""".strip()
    (outdir / "README_expected_vs_observed.txt").write_text(text + "\n", encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser(
        description="Plot expected ART simulation design against observed CMV pipeline outputs."
    )
    ap.add_argument("--truth", required=True, help="Path to truth/metadata.tsv from the simulator")
    ap.add_argument("--csv-dir-1", required=True, help="First pipeline output directory")
    ap.add_argument("--csv-dir-2", required=True, help="Second pipeline output directory")
    ap.add_argument("--csv-dir-3", required=True, help="Third pipeline output directory")
    ap.add_argument("--outdir", required=True, help="Output directory")
    args = ap.parse_args()

    outdir = Path(args.outdir)
    figdir = outdir / "figures"
    ensure_dir(outdir)
    ensure_dir(figdir)

    csv_dirs = collect_csv_dirs(args)

    truth = load_truth(Path(args.truth))
    bam = load_alignment_summaries(csv_dirs)
    blast = load_blast_top5(csv_dirs)

    expected_vs_observed = build_expected_vs_observed_table(truth, bam, blast)
    group_summary = build_group_summary(expected_vs_observed)

    truth.sort_values(["group", "sample"]).to_csv(outdir / "simulation_design_table.tsv", sep="\t", index=False)
    expected_vs_observed.to_csv(outdir / "sample_expected_vs_observed.tsv", sep="\t", index=False)
    expected_vs_observed.to_csv(outdir / "sample_expected_vs_observed.csv", index=False)
    group_summary.to_csv(outdir / "group_expected_vs_observed_summary.tsv", sep="\t", index=False)

    plot_group_expected_vs_observed_overview(group_summary, figdir / "group_expected_vs_observed_overview.png")
    plot_sample_expected_vs_observed_proxy_fraction(expected_vs_observed, figdir / "sample_expected_vs_observed_proxy_fraction.png")
    plot_roc_ladder_expected_vs_observed(expected_vs_observed, figdir / "roc_ladder_expected_vs_observed.png")
    plot_sample_composition_expected(expected_vs_observed, figdir / "sample_composition_expected.png")
    write_readme(outdir)

    print("Done.")
    print(f"Simulation design: {outdir / 'simulation_design_table.tsv'}")
    print(f"Expected/observed: {outdir / 'sample_expected_vs_observed.tsv'}")
    print(f"Group summary:     {outdir / 'group_expected_vs_observed_summary.tsv'}")
    print(f"Figures:           {figdir}")


if __name__ == "__main__":
    main()